### ISSUE TITLE
1.14.8 - Failed resolution of: Llib/android/paypal/com/magnessdk/MagnesSDK; 

### ISSUE THREAD

**Issue by planetcoops** [iZettle/sdk-android#23]
# Expected Behavior

# Current Behavior

What is the current behavior?

App crashes with the following stack:

--- STACK ---
java.lang.NoClassDefFoundError: Failed resolution of: Llib/android/paypal/com/magnessdk/MagnesSDK;
at com.izettle.payments.android.payment.TransactionsManager$Companion$a.a(Line:1)
at com.izettle.payments.android.payment.TransactionsManager$Companion$a.invoke(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl.getReferenceWithMagnesClientId$payment_release(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl.createAndStartTransaction(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl.reduce(Line:2)
at com.izettle.payments.android.payment.TransactionsManagerImpl.reduce$payment_release(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl$c.a(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl$c.invoke(Line:1)
at com.izettle.android.commons.state.StateImpl.update(Line:4)
at com.izettle.payments.android.payment.TransactionsManagerImpl.action(Line:1)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl.mutate$view_models_release(Line:10)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl$a.a(Line:1)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl$a.invoke(Line:1)
at com.izettle.android.commons.state.StateImpl.update(Line:7)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl.action(Line:1)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl.access$action(Line:1)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl$$special$$inlined$stateObserver$1.onNext(Line:2)
at com.izettle.android.commons.state.StateImpl$b.a(Line:1)
at com.izettle.android.commons.state.StateImpl$b.invoke(Line:1)
at com.izettle.android.commons.thread.a.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ClassNotFoundException: lib.android.paypal.com.magnessdk.MagnesSDK
... 27 more

# Steps to Reproduce

Initiate a payment when using com.izettle.payments:android-sdk-ui:1.14.8

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Phone Model: Pixel 2
Android Version: 11
Board: walleye
Brand: google
Device: walleye
Display: RP1A.201005.004.A1
Finger Print: google/walleye/walleye:11/RP1A.201005.004.A1/6934943:user/release-keys
Host: abfarm873
ID: RP1A.201005.004.A1
Manufacturer: Google
Model: Pixel 2
Product: walleye
Tags: release-keys
Time: 1603833891000
Type: user
User: android-build
Total Internal Memory: 56040513536
Available Internal Memory: 20652740608

## Failure Logs

Please include any relevant log snippets or files here.

--- STACK ---
java.lang.NoClassDefFoundError: Failed resolution of: Llib/android/paypal/com/magnessdk/MagnesSDK;
at com.izettle.payments.android.payment.TransactionsManager$Companion$a.a(Line:1)
at com.izettle.payments.android.payment.TransactionsManager$Companion$a.invoke(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl.getReferenceWithMagnesClientId$payment_release(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl.createAndStartTransaction(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl.reduce(Line:2)
at com.izettle.payments.android.payment.TransactionsManagerImpl.reduce$payment_release(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl$c.a(Line:1)
at com.izettle.payments.android.payment.TransactionsManagerImpl$c.invoke(Line:1)
at com.izettle.android.commons.state.StateImpl.update(Line:4)
at com.izettle.payments.android.payment.TransactionsManagerImpl.action(Line:1)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl.mutate$view_models_release(Line:10)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl$a.a(Line:1)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl$a.invoke(Line:1)
at com.izettle.android.commons.state.StateImpl.update(Line:7)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl.action(Line:1)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl.access$action(Line:1)
at com.izettle.payments.android.models.payment.PaymentViewModelImpl$$special$$inlined$stateObserver$1.onNext(Line:2)
at com.izettle.android.commons.state.StateImpl$b.a(Line:1)
at com.izettle.android.commons.state.StateImpl$b.invoke(Line:1)
at com.izettle.android.commons.thread.a.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ClassNotFoundException: lib.android.paypal.com.magnessdk.MagnesSDK
... 27 more

**Comment by planetcoops** [comment]
Issue appears to have been resolved with SDK version 1.14.9.
