### ISSUE TITLE
Can't complete OAuth login flow after upgrading from 1.25.6 to 1.30.1

### ISSUE THREAD

**Issue by planetcoops** [iZettle/sdk-android#69]
# Expected Behavior

After logging in and authorizing the app, the flow should return to the client app with a valid access token, prompting the user to select card readers.

# Current Behavior

App remains on the page with the login button.  The app doesn't appear to receive the OAuth access token.

# Steps to Reproduce

Update a previously working integration from 1.25.6 to 1.30.1

Are there any related known issues with 1.30.1 that are being worked on?  Has anyone else reported similar issues after upgrading to 1.30.1?

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Tested on Android Version: 30, 31
* Android Target SDK version: 32

## Logs

Here's the request to the browser:

2022-07-08 13:44:33.404 20232-20232/com.planetcoops.android.taximeter I/AuthWebLauncherImpl: Launching browser with URI https://oauth.zettle.com/authorize?client_id=[redacted]&scope=READ%3APAYMENT%20WRITE%3APAYMENT%20READ%3AUSERINFO&redirect_uri=com.planetcoops.taximeter%3A%2F%2Fauth&code_challenge=W8w60LUSwxLY0EKDSGCJKA5gHNkJA51Ll0Vd6h_u7Co&code_challenge_method=S256&response_type=code&app=payments-sdk&prompt=login&app_version=1.1.130&os=android&os_version=30&udid=ADb45e84249597414bb782a0f3578b8fd8ec07c4&locale=en-GB&state=eyJjYWxsaW5nQWN0aXZpdHlDbGFzcyI6ImNvbS5pemV0dGxlLnBheW1lbnRzLmFuZHJvaWQudWkucGF5bWVudC5DYXJkUGF5bWVudEFjdGl2aXR5IiwidGFza0lkIjoiODdjNWY5MDktMWI1Yi00ZDczLTg5Y2MtZDhlOTgwMjZmMjFhIiwidGFza1R5cGUiOiJjb20uaXpldHRsZS5hbmRyb2lkLmF1dGgudGFza3MuT0F1dGhMb2dpblRhc2sifQ
        at com.izettle.android.auth.log.StackTraceKt.withStackTrace(SourceFile:1)
        at com.izettle.android.auth.AuthWebLauncherImpl.launchInBrowser(SourceFile:1)
        at com.izettle.android.auth.OAuthActivity.onResume(SourceFile:10)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8135)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by planetcoops** [comment]
Issue resolved in version release-1.32.0
